Update branch_rule_main.restrict-pr.yml

diff --git a/.github/workflows/branch_rule_main.restrict-pr.yml b/.github/workflows/branch_rule_main.restrict-pr.yml
--- a/.github/workflows/branch_rule_main.restrict-pr.yml
+++ b/.github/workflows/branch_rule_main.restrict-pr.yml
@@ -50,8 +50,8 @@ jobs:
           # Output the detected parent branch
           echo "Detected parent branch: $PARENT_BRANCH"
           
-          # Check if we are merging into 'main' and if the current branch is valid
-          if [[ "$PARENT_BRANCH" == "main" ]] && [[ ! "$CURRENT_BRANCH" =~ ^hotfix/.* ]] && [[ "$CURRENT_BRANCH" != "dev" ]]; then
-            echo "Error: Only PRs from 'dev' or 'hotfix/*' branches are allowed to merge into 'main'."
-            exit 1
-          fi
+          # # Check if we are merging into 'main' and if the current branch is valid
+          # if [[ "$PARENT_BRANCH" == "main" ]] && [[ ! "$CURRENT_BRANCH" =~ ^hotfix/.* ]] && [[ "$CURRENT_BRANCH" != "dev" ]]; then
+          #   echo "Error: Only PRs from 'dev' or 'hotfix/*' branches are allowed to merge into 'main'."
+          #   exit 1
+          # fi
